Physical Filter Operator
LiUSemWeb/HeFQUIN pull request #173
Opened 2022-03-24 15:21 UTC by SHSenpai

> You need to create a new class called `PhysicalOpFilter`. This class should go into the Java package `se.liu.ida.hefquin.engine.queryplan.physical.impl` and it should implement the `UnaryPhysicalOpForLogicalOp` interface.
> 
> It should have a `LogicalOpFilter` as a member variable, assigned through the constructor.
> 
> The `createExecOp` function that you need to implement in this class should create and return an `ExecOpFilter` and it can ignore the `inputVars` argument.
> 
> The `getExpectedVariables` function that you need to implement in this class should check that the `inputVars` argument is an array of length 1 (otherwise throw an IllegalArgumentException) and, then, it should simply return the one `ExpectedVariables` object contained in that array.

Done as far as my current understanding goes. Builds well and all tests should run.

2022-03-25 15:25 UTC, hartig requested changes
Just a few minor things.

2022-03-25 15:25 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpFilter.java
> +	public PhysicalOpFilter(LogicalOpFilter lf) {
```suggestion
	public PhysicalOpFilter( final LogicalOpFilter lf ) {
```

2022-03-25 15:25 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpFilter.java
> +	public ExpectedVariables getExpectedVariables(ExpectedVariables... inputVars) {
```suggestion
	public ExpectedVariables getExpectedVariables( final ExpectedVariables... inputVars ) {
```

2022-03-25 15:25 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpFilter.java
> +	public void visit(PhysicalPlanVisitor visitor) {
```suggestion
	public void visit( final PhysicalPlanVisitor visitor ) {
```

2022-03-28 08:48 UTC, hartig commented
Once you have resolved the minor issues mentioned in my review of this PR, I will merge this PR.

After that, the new operator needs to be integrated into our query processor. To this end, in another PR, please extend the class `LogicalToPhysicalOpConverter`. In particular, the function `convert(UnaryLogicalOp)` needs to be extended.

2022-03-28 09:41 UTC, SHSenpai commented
Updated. At times like these when all the still-needed changes are known, could I merge it myself so that I could immediately resume work on a new branch coming from the main branch?

2022-03-28 10:55 UTC, hartig approved these changes

2022-03-28 10:55 UTC, merged

2022-03-28 10:57 UTC, hartig commented
Merged.

To your question: yes, good idea. I will indicate in my future reviews whether you can directly merge after addressing the points in the review.