ExecOpRequestSPARQLWithTranslation
LiUSemWeb/HeFQUIN pull request #179
Opened 2022-04-12 12:03 UTC by JulietteVV

2022-04-25 10:59 UTC, JulietteVV commented
@scferrada About the original request, you mentioned that it could not be a union but could it be a SPARQLGroupPattern? Or was it only TriplePattern and BGP?

2022-04-25 11:15 UTC, scferrada commented
I think it should only be TriplePattern or BGP, because we have defined the translation method only for those two.

However, it seems that translating unions (of TriplePatterns and BGPs) is straightforward, right? In which case we could leave that code, and maybe mention it in the thesis, if it is not too long.

2022-04-25 12:56 UTC, JulietteVV commented
> I think it should only be TriplePattern or BGP, because we have defined the translation method only for those two.
> 
> However, it seems that translating unions (of TriplePatterns and BGPs) is straightforward, right? In which case we could leave that code, and maybe mention it in the thesis, if it is not too long.

I think I can explain in the text how translating a more complex subquery such as a union would be done. Because as long as the triples in the union's subpaterns are handled seperately the translation itself would be the same.

2022-04-25 13:07 UTC, scferrada commented
Ok, we can do that then :D!

2022-05-11 19:31 UTC, hartig requested changes
Besides the smaller issues mentioned in my comments in the code, there are two additional things that need to be added:

1/ The if-else-if-... part in `performRequest` does not cover all relevant cases. There are also two classes that implement `SPARQLGraphPattern` directly, namely `GenericSPARQLGraphPatternImpl1` and `GenericSPARQLGraphPatternImpl2`. These classes may be used in requests to SPARQL endpoints and, thus, need to be handled here. Both of them have a `asJenaOp()` function that returns the graph pattern in the form of a Jena `Op` object. In particular, there are different relevant subclasses of `Op`, namely:
* `OpJoin` (should be handled like a `SPARQLGroupPattern`),
* `OpUnion` (should be handled like a `SPARQLUnionPattern`),
* `OpFilter` (tricky, I am not sure what to do with it -- let's ignore it for the moment),
* `OpBGP` (should be handled like a `BGP`),
* `OpSequence` (should be handled like a `SPARQLGroupPattern`).

2/ As I had mentioned in your other PR (#177), it is problematic to change `PhysicalOpRequest` as you do here. Instead, the new class `PhysicalOpRequestWithTranslation` that I had added to  PR #177 needs to be used here as well. Maybe, before you start redoing PR #177 (for which we said you need to include the new class `PhysicalOpRequestWithTranslation`), you include this class here and then start the redoing of PR #177 only after this PR here is merged. Note that it is not only that one new class, some other classes where affected too; it is all in this one commit that I had made in PR #177.

2022-05-13 16:45 UTC, hartig requested changes
Great. All my comments are addressed. Now, I only have a few additional comments; mostly improvements to the code. You can commit all my change suggestions together in a batch (there is a feature for that on the github page for the PR).

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +			for (SolutionMapping smTranslated : fm.getVocabularyMapping().translateSolutionMapping(sm)) {
```suggestion
		for ( final SolutionMapping sm : response.getSolutionMappings() ) {
			for ( final SolutionMapping smTranslated : fm.getVocabularyMapping().translateSolutionMapping(sm) ) {
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +			reqTranslation = handleOp(gp);
```suggestion
		final SPARQLGraphPattern reqTranslation;
		if (query instanceof TriplePattern) {
			reqTranslation = handleTriplePattern((TriplePattern) query);	
		} 
		else if (query instanceof BGP) {
			reqTranslation = handleBGP((BGP) query);
		}
		else if (query instanceof SPARQLGroupPattern) {
			reqTranslation = handleGroup((SPARQLGroupPattern) query);
		}
		else if (query instanceof SPARQLUnionPattern) {
			reqTranslation = handleUnion((SPARQLUnionPattern) query);
		}
		else if (query instanceof GenericSPARQLGraphPatternImpl1) {
			final Op gp = ((GenericSPARQLGraphPatternImpl1) query).asJenaOp();
			reqTranslation = handleOp(gp);		
		}
		else if (query instanceof GenericSPARQLGraphPatternImpl2) {
			final Op gp = ((GenericSPARQLGraphPatternImpl2) query).asJenaOp();
			reqTranslation = handleOp(gp);	
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +	protected SPARQLGraphPattern handleTriplePattern(TriplePattern tp) {
```suggestion
	
	
	protected SPARQLGraphPattern handleTriplePattern( final TriplePattern tp ) {
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +	protected SPARQLGraphPattern handleBGP(BGP bgp) {
```suggestion
	protected SPARQLGraphPattern handleBGP( final BGP bgp ) {
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +	protected SPARQLGraphPattern handleUnion(SPARQLUnionPattern up) throws FederationAccessException {
```suggestion
	protected SPARQLGraphPattern handleUnion( final SPARQLUnionPattern up ) throws FederationAccessException {
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +				throw new FederationAccessException(i.toString(), req, fm);
```suggestion
				throw new FederationAccessException("Unsupported type of pattern: " + i.getClass().getName(), req, fm);
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +	protected SPARQLGraphPattern handleGroup(SPARQLGroupPattern gp) throws FederationAccessException {
```suggestion
	protected SPARQLGraphPattern handleGroup( final SPARQLGroupPattern gp ) throws FederationAccessException {
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +		List<SPARQLGraphPattern> subPatterns = new ArrayList<>();
```suggestion
		final List<SPARQLGraphPattern> subPatterns = new ArrayList<>();
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +				throw new FederationAccessException(i.toString(), req, fm);
```suggestion
				throw new FederationAccessException("Unsupported type of pattern: " + i.getClass().getName(), req, fm);
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +	protected SPARQLGraphPattern handleOp(Op op) throws FederationAccessException {
```suggestion
	protected SPARQLGraphPattern handleOp( final Op op ) throws FederationAccessException {
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +		subPatterns.add(handleOp(right));
```suggestion
	protected SPARQLGraphPattern handleJoin( final OpJoin oj ) throws FederationAccessException {
		final List<SPARQLGraphPattern> subPatterns = new ArrayList<>();
		final Op left = oj.getLeft();
		subPatterns.add(handleOp(left));
		final Op right = oj.getRight();
		subPatterns.add(handleOp(right));
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +		Op right = ou.getRight();
```suggestion
	protected SPARQLGraphPattern handleOpUnion( final OpUnion ou ) throws FederationAccessException {
		final SPARQLUnionPatternImpl unionTranslation = new SPARQLUnionPatternImpl();
		final Op left = ou.getLeft();
		unionTranslation.addSubPattern(handleOp(left));
		final Op right = ou.getRight();
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +		return null;
No!! Simply returning `null` here is a guarantee for giving us headaches later when we all of a sudden have an unexpected `null` somewhere in a rewritten query pattern. To make sure we will always know that there was an unhandled case, throw an exception here (or remove this method and the corresponding case in the `handleOp(Op)` function).

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +	protected SPARQLGraphPattern handleOpBGP(OpBGP obgp) throws FederationAccessException {
```suggestion
	protected SPARQLGraphPattern handleOpBGP( final OpBGP obgp ) throws FederationAccessException {	
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +			TriplePattern itp = new TriplePatternImpl(i);
```suggestion
			final TriplePattern itp = new TriplePatternImpl(i);
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpRequestSPARQLWithTranslation.java
> +		List<SPARQLGraphPattern> subPatterns = new ArrayList<>();
```suggestion
	protected SPARQLGraphPattern handleOpSequence( final OpSequence os ) throws FederationAccessException {
		final List<SPARQLGraphPattern> subPatterns = new ArrayList<>();
```

2022-05-13 16:45 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpRequest.java
> +			}
No. Please remove that. This case will be covered by the new `PhysicalOpRequestWithTranslation` class.

2022-05-13 19:40 UTC, hartig approved these changes
Now this PR is ready to merge. Thanks!

2022-05-13 19:40 UTC, merged