Add CombinedEdgeLabelMapping
LiUSemWeb/HeFQUIN pull request #317
Opened 2023-11-07 22:22 UTC by BentolhodaH

Add CombinedEdgeLabelMapping and its tests
Encapsulate creating EdgeLabelMapping into different functions to avoid duplicate code 
Add UnSupportedEdgeLabelException

2023-11-07 22:29 UTC, BentolhodaH commented
In 'RunBGPOverNeo4j.java,' currently, we are not reading the TTL file. It is necessary to specify a command-line argument to obtain the file address, similar to the file query file address. In this step, should I make modifications to that part to read from the example file instead of creating classes manually?

2023-11-08 05:24 UTC, hartig commented
Indeed. The command-line tool needs to be extended to provide such an argument. Please do that, but in a separate PR. In terms of implementing it, it should be implemented more like the argument for the federation catalog that we have in the other command-line tool.

2023-11-08 07:33 UTC, hartig requested changes
A few minor things.

2023-11-08 07:33 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedEdgeLabelMappingToURIsImpl.java
> +        for (EdgeLabelMapping edgeLabelMapping : edgeLabelMappings) {
```suggestion
        for ( final EdgeLabelMapping edgeLabelMapping : edgeLabelMappings ) {
```

2023-11-08 07:33 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedEdgeLabelMappingToURIsImpl.java
> +        for (EdgeLabelMapping edgeLabelMapping : edgeLabelMappings) {
```suggestion
        for ( final EdgeLabelMapping edgeLabelMapping : edgeLabelMappings ) {
```

2023-11-08 07:33 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedEdgeLabelMappingToURIsImpl.java
> +        for (EdgeLabelMapping edgeLabelMapping : edgeLabelMappings) {
```suggestion
        for ( final EdgeLabelMapping edgeLabelMapping : edgeLabelMappings ) {
```

2023-11-08 07:33 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedEdgeLabelMappingToURIsImpl.java
> +            catch (IllegalArgumentException exception) {}
Shouldn't this be `UnSupportedEdgeLabelException` ?

2023-11-10 21:21 UTC, hartig approved these changes
Thanks!!

2023-11-10 21:22 UTC, merged