Make PropertyNameMapping more flexible.
LiUSemWeb/HeFQUIN pull request #320
Opened 2023-11-17 10:05 UTC by BentolhodaH

2023-11-17 13:19 UTC, hartig requested changes
Several minor things ...

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +        catch (IllegalArgumentException exception){
```suggestion
        catch ( final IllegalArgumentException e ){
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +            throw new IllegalArgumentException("prefixOfIRIs is an invalid URI!");
If a developer gets this error message for an LPG-to-RDF description that contains several `lr:prefixOfIRIs` triples, he/she would not know which URI this message refers to. Therefore, better be explicit:
```suggestion
            throw new IllegalArgumentException("prefixOfIRIs ( + prefixOfIRIUri + ) is an invalid URI!");
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +            throw new IllegalArgumentException("prefixOfIRIs is an invalid URI!");
Please also double check the other error messages throughout this PR for similar issues.

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +    public PropertyNameMapping createSinglePropertyNameMapping(final Resource propertyNameMappingResource){
```suggestion
    }

    public PropertyNameMapping createSinglePropertyNameMapping(final Resource propertyNameMappingResource){
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +        } catch (IllegalArgumentException exception) {
```suggestion
        } catch ( final IllegalArgumentException e ) {
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +        } catch (IllegalArgumentException exception) {
```suggestion
        } catch ( final IllegalArgumentException e ) {
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +    public PropertyNameMapping createCombinedPropertyNameMapping(final Resource propertyNameMappingResource){
```suggestion
    }

    public PropertyNameMapping createCombinedPropertyNameMapping(final Resource propertyNameMappingResource){
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
> +        else if ( propertyNameMappingResourceType.equals(LPG2RDF.SinglePropertyNameMapping)
```suggestion
        }
        else if ( propertyNameMappingResourceType.equals(LPG2RDF.SinglePropertyNameMapping)
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/LPG2RDFConfigurationReader.java
>      public PropertyNameMapping getPropertyNameMapping(final Model lpg2Rdf, final Resource lpg2rdfConfig){
```suggestion
    }

    public PropertyNameMapping getPropertyNameMapping(final Model lpg2Rdf, final Resource lpg2rdfConfig){
```

2023-11-17 13:19 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/SinglePropertyNameMappingToURIsImpl.java
> +    @Override
```suggestion
    }

    @Override
```

2023-11-18 21:08 UTC, BentolhodaH commented on src/main/java/se/liu/ida/hefquin/engine/wrappers/lpgwrapper/impl/CombinedPropertyNameMappingToURIsImpl.java
> +public class CombinedPropertyNameMappingToURIsImpl implements PropertyNameMapping {
I chose that name because all the PropertyName class names have "toURIs," and they work with URIs (not blanks or literals).

2023-11-19 07:49 UTC, hartig approved these changes
Thanks!

2023-11-19 07:49 UTC, merged