Values bind join
LiUSemWeb/HeFQUIN pull request #38
Opened 2021-05-10 15:55 UTC by scferrada

Tests aren't passing because of a ``ClassCastException``, where the test suite tries to cast a ``SPARQLGraphPattern`` into a ``TriplePattern`` on the ``performRequest`` method. Not sure if that is the expected behaviour.

2021-05-10 21:08 UTC, hartig commented
This is for #32

2021-05-10 21:13 UTC, hartig requested changes

2021-05-10 21:13 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpVALUESBindJoin.java
> +	protected PhysicalOpVALUESBindJoin(UnaryLogicalOp lop) {
```suggestion
	public PhysicalOpVALUESBindJoin( final UnaryLogicalOp lop ) {
```

2021-05-10 21:13 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpVALUESBindJoin.java
> +	public UnaryExecutableOp createExecOp(ExpectedVariables... inputVars) {
```suggestion
	public UnaryExecutableOp createExecOp( final ExpectedVariables... inputVars ) {
```

2021-05-10 21:13 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryplan/physical/impl/PhysicalOpVALUESBindJoin.java
> +public class PhysicalOpVALUESBindJoin extends BasePhysicalOpSingleInputJoin {
Please rename this class to `PhysicalOpBindJoinWithVALUES`.

2021-05-10 21:13 UTC, hartig commented on src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithVALUESTest.java
> +	protected SPARQLEndpoint createFedMemberForTest(Graph dataForMember) {
```suggestion
	protected SPARQLEndpoint createFedMemberForTest( final Graph dataForMember ) {
```

2021-05-10 21:13 UTC, hartig commented on src/test/java/se/liu/ida/hefquin/engine/queryplan/executable/impl/ops/ExecOpBindJoinSPARQLwithVALUESTest.java
> +	protected UnaryExecutableOp createExecOpForTest(TriplePattern tp, SPARQLEndpoint fm) {
```suggestion
	protected UnaryExecutableOp createExecOpForTest( final TriplePattern tp, final SPARQLEndpoint fm ) {
```

2021-05-10 21:22 UTC, hartig commented
> Tests aren't passing because of a `ClassCastException`, where the test suite tries to cast a `SPARQLGraphPattern` into a `TriplePattern` on the `performRequest` method.

I am afraid the test suite (`EngineTestBase`) needs to be extended to be able to deal with cases in which the given `SPARQLRequest` is not a `TriplePatternRequest` and its query pattern is not a `TriplePattern` but just a `SPARQLGraphPattern` with an `Op` object. For such a case, there should be a way to have Jena execute that `Op` operator over the given `Graph`. Can you please add this.

2021-05-11 14:07 UTC, hartig requested changes

2021-05-11 14:09 UTC, hartig commented
...plus the failing unit test.

2021-05-11 17:36 UTC, scferrada commented
All tests pass now

2021-05-11 19:02 UTC, merged