first implementation for printing logical plans
LiUSemWeb/HeFQUIN pull request #47
Opened 2021-05-24 16:09 UTC by scferrada

Here is a first attempt on printing Logical plans, based in the available Visitor and Walker classes.  I added a second walk method to transverse the tree from top down. 

Since the visitor does not know the level it is at, tabulation currently works as a best guess. This can be improved by coupling the walk method with the visitor class to indicate the current depth, the parent of the operator and the position of the current Op in the child list.

I'm opening the PR to discuss those issues as well as the visitor/walker structure in general.

2021-05-24 21:10 UTC, hartig commented
related to #27

2021-05-24 22:01 UTC, hartig requested changes
I have added several review comments.

Additionally, I think that the current idea with the indentation is not going to work at all. A better idea would be to extend the `WalkerVisitor` class inside `LogicalPlanWalker` such that it may be initialized with two separate `LogicalPlanVisitor` objects, where one of them is called as a "before visitor" (before going into subplans) and the other as an "after visitor" (after having gone into subplans). Hence, the code of the extended `WalkerVisitor` class may look as follows:
```java
protected static class WalkerVisitor {
	protected final LogicalPlanVisitor beforeVisitor;
	protected final LogicalPlanVisitor afterVisitor;

	public WalkerVisitor( final LogicalPlanVisitor beforeVisitor, final LogicalPlanVisitor afterVisitor ) {
		this.beforeVisitor = beforeVisitor;
		this.afterVisitor = afterVisitor;
	}

	public void walk( final LogicalPlan plan ) {
		if ( beforeVisitor != null ) {
			plan.getRootOperator().visit(beforeVisitor);
		}
		for ( int i = 0; i < plan.numberOfSubPlans(); ++i ) {
			walk( plan.getSubPlan(i) );
		}
		if ( afterVisitor != null ) {
			plan.getRootOperator().visit(afterVisitor);
		}
	}
}
```
Of course, the static method `walk` in `LogicalPlanWalker` has to be extended accordingly.

Once this is in place, there can be a `LogicalPlanPrinter` class that has two implementations of `LogicalPlanVisitor` (one of which as the corresponding "before visitor" and the other one as the "after visitor") such that both access the same `indentLevel` variable of the `LogicalPlanPrinter`. Then, for instance, for the join operator, the "before visitor" prints the info about the join operator and, afterwards, increases the `indentLevel`, and the "after visitor" simply decreases the `indentLevel` again.

2021-05-25 13:04 UTC, hartig requested changes
Only one small thing -- see my review comment.

Except for that, it looks good! Good job.

Please only address the last remaining issue in this PR, instead of also adding something for the executable plans here. Once this PR is merged, you can create a separate PR for the printer of the executable plans.

2021-05-25 13:07 UTC, scferrada commented
> Please only address the last remaining issue in this PR, instead of also adding something for the executable plans here. Once this PR is merged, you can create a separate PR for the printer of the executable plans.

Given that my other PR was merged I will need to rebase from main, to include the UNION physical operator

2021-05-25 13:20 UTC, hartig commented
Oops! I didn't realize there was a conflict between the PRs.

2021-05-25 14:27 UTC, hartig requested changes

2021-05-25 14:27 UTC, hartig commented on .gitignore
> +>>>>>>> 6e96eb9d74b6839c61a31117a25ad65797e00edd
This doesn't look right.

2021-05-25 15:33 UTC, scferrada commented
I added a new commit with a small change and I think now you can merge.

2021-05-25 17:25 UTC, merged

2021-05-25 17:26 UTC, hartig commented
Thanks! Merged.