Dynamic programming
LiUSemWeb/HeFQUIN pull request #65
Opened 2021-07-06 14:18 UTC by chengsijin0817

2021-07-08 16:53 UTC, hartig requested changes

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +    protected List<PhysicalPlan> lpList;
```suggestion
    protected final List<PhysicalPlan> lpList;
```

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +    protected PhysicalPlan optimizePhysicalPlanForMultiwayJoin() throws FederationAccessException {
Shouldn't this method be public, given that this is the actual main method you are calling when using this class. 

Also, the methods here should not throw a FederationAccessException but a QueryOptimizationException.

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +    public PhysicalPlan chooseFirstSubquery() throws FederationAccessException {
QueryOptimizationException

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +        assert ctxt != null;
```suggestion
        assert ctxt != null;
        assert lpList.size() > 0;
```

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +    public PhysicalPlan chooseFirstSubquery() throws FederationAccessException {
Also, this method should be protected rather than public. You don't want it to be called from the outside.

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +public class DynamicProgramming extends CardinalityEstimation {
It doesn't make sense to make this class a subclass of CardinalityEstimation. Instead, pass a CardinalityEstimation object to the constructor of this class. This way, we can use different implementations of CardinalityEstimation in the future.

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +            initialCost = cost;
This line should be inside the if branch.

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +            initialCost = cost;
Same issue here, this line should be inside the if branch.

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/DynamicProgramming.java
> +        final PhysicalPlan ppNew = new PhysicalPlanWithBinaryRootImpl( convertJoin( new LogicalOpJoin() ), currentPlan, nextPlan);
Haven't you already created this plan above?

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +    public PhysicalPlan optimize( final LogicalPlan initialPlan ) throws FederationAccessException {
These methods here should not throw a FederationAccessException but a QueryOptimizationException.

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +        if ( lop instanceof NaryLogicalOp ) {
A multiway union is also an NaryLogicalOp but that one should not be passed to the DP algorithm.

2021-07-08 16:53 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +        final List<PhysicalPlan> children = findChildren(pp);
Move this line into the if branch.

2021-07-08 21:55 UTC, hartig requested changes

2021-07-08 21:55 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +    public PhysicalPlan optimize( final LogicalPlan initialPlan ) throws FederationAccessException, QueryOptimizationException {
As in the other PR, none of these public methods should declare to throw FederationAccessException.

2021-07-08 21:55 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +    public List<PhysicalPlan> findChildren( final PhysicalPlan pp ) throws FederationAccessException, QueryOptimizationException {
This is an internal helper method and, thus, shouldn't be public but protected.

2021-07-08 21:55 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +        if ( numChildren > 0 ) {
This if test is not needed. Your for loop handles the case of `numChildren==0` correctly.

2021-07-08 21:55 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +        else if (children.size() == 1 ){
Can you please try to be consistent in how you are formatting your code. For instance, this else-if branch is wrapped in curly braces and appears on a new line, whereas the if branch directly above does not have curly braces ... but at least it also is on a new, which is not always the case in this and the other PR.  Another example: in this line here you have no space between the opening parenthesis and the if condition, but two lines before you do.

2021-07-08 21:55 UTC, hartig commented on src/main/java/se/liu/ida/hefquin/engine/queryproc/impl/optimizer/dynamicProgramming/WrappingDPAlgorithm.java
> +        DynamicProgramming dp= new DynamicProgramming(ctxt, children);
```suggestion
        final DynamicProgramming dp = new DynamicProgramming(ctxt, children);
```

2021-07-09 15:41 UTC, hartig approved these changes
This one looks good too. I would merge it but I notice that it contains parts of the other PR (#64). Therefore, I am not sure whether it can simply be merged after merging the other one. I can try if you are okay with it. Okay?

2021-07-09 16:45 UTC, chengsijin0817 commented
> This one looks good too. I would merge it but I notice that it contains parts of the other PR (#64). Therefore, I am not sure whether it can simply be merged after merging the other one. I can try if you are okay with it. Okay?

Sure. I am also okay with merging this PR.

2021-07-09 16:55 UTC, merged